### PR TITLE
Move special Markdown line break whitespace handling to configuration

### LINKED ISSUE #68: failing to remove whitespace from markdown file
I ran into a markdown file that had a bunch of trailing whitespace. None of it was actually required for it to render properly, it was just there by mistake. So I opened & saved the file with Atom, expecting it to be stripped, but only some of it was (all the lines with 2 trailing spaces remained). Using the "Whitespace: Remove Trailing Whitespace" command also failed to strip it.

I think that [this is the code responsible](https://github.com/atom/whitespace/blob/466e130328e3ddd2a097989b6f4edc256d084bd3/lib/whitespace.coffee#L60) - some special logic for leaving 2 spaces alone in GFM.

I propose that we either remove this, since nearly the same thing can be accomplished if people who use trailing whitespace in their markdown added the following to their config:

```cson
".gfm.source":
  whitespace:
    removeTrailingWhitespace: false
```

...or at least make enabling it an option, since I only found out about it by reading the source.

### PR DESCRIPTION
**Pull request by lee-dohm**
Fixes #68, #80 

Moving it to a configuration setting allows it to be turned off.

### CODE REVIEW

File: lib/main.coffee [hunk 1]
```diff
@@ -8,6 +8,9 @@ module.exports =
       scopes:
         '.source.jade':
           default: false
+    ignoreMarkdownLineBreak:
+      type: 'boolean'
```
Comment (kevinsawicki) [inline lib/main.coffee]: I think this needs a description or an improved name, it would take me awhile to think about whether checked or unchecked will trim trailing whitespace in markdown files since "ignoring the line break" means removing it in the context of this package.

Maybe something like:

* `keepTrailingTwoSpacesInMarkdownFiles` with a description like *Markdown treats two spaces at the end of a line as a line break*

Thoughts?

Comment (lee-dohm) [inline lib/main.coffee]: Changed the name to `keepMarkdownLineBreakWhitespace` and added the following description:

> Markdown uses two ore more spaces at the end of a line to signify a line break. Enable this option to keep this whitespace, even if other settings would remove it.

File: lib/main.coffee [hunk 2]
```diff
@@ -8,6 +8,13 @@ module.exports =
       scopes:
         '.source.jade':
           default: false
+    keepMarkdownLineBreakWhitespace:
+      type: 'boolean'
+      default: true
+      description: '''
```
Comment (kevinsawicki) [inline lib/main.coffee]: What a nice description :+1:

Comment (lee-dohm) [inline lib/main.coffee]: Thanks!

**Comment by mnquintana** [comment]
:+1: :ship:

**Comment by lee-dohm** [comment]
Thanks!
